<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="ManageClinic.aspx.cs" Inherits="DBProject.ManageClinic" %>

<script runat="server">


</script>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
</asp:Content>




<asp:Content ID="Content2" ContentPlaceHolderID="head" runat="server">

    <%--<style type = "text/css">

    .outer {
       margin-left:20%;
       display:inline-block;
  
     

    }
    .mydiv
    {
        display:inline-block;
    }

</style>--%>
</asp:Content>









<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <form runat="server">


        <h2 class="font-weight-bold">Manage Clinic</h2>

        <hr />




        <div class="p-1">
            <div class="form-row bg-white border rounded mb-2 ">
                <%--<div class="col">
                    Select Catagory :
                </div>--%>
                <div class="col border p-2">
                    <asp:RadioButton name="Gender" OnCheckedChanged="RadioButton_CheckedChanged"
                        AutoPostBack="true" ID="Doctor" GroupName="Catagory" runat="server" Text=" Doctor" Checked="true" value="D" />
                </div>
                <div class="col border p-2">
                    <asp:RadioButton name="Gender" OnCheckedChanged="RadioButton_CheckedChanged"
                        AutoPostBack="true" ID="Patient" GroupName="Catagory" runat="server" Text=" Patient" value="P" />
                </div>
                <div class="col border p-2">
                    <asp:RadioButton name="Gender" OnCheckedChanged="RadioButton_CheckedChanged"
                        AutoPostBack="true" ID="OtherStaff" GroupName="Catagory" runat="server" Text=" Other Staff" value="O" />
                </div>
            </div>
        </div>






        <div class="input-group">
            <div class="input-group-prepend">
                <asp:Button Text="Search" runat="server" type="submit" class="btn btn-primary" OnClick="Search_btn"></asp:Button>
            </div>
            <asp:TextBox ID="txtSearch" CssClass="form-control" runat="server" />
        </div>

        <br />
        <asp:Label ID="Msg" runat="server" Font-Bold="True"></asp:Label>

        <div class="row">
            <div class="col">
                <div class="table-responsive">

                    <asp:GridView
                        ID="Manage"
                        AutoGenerateDeleteButton="True"
                        EnableViewState="False"
                        OnRowDeleting="DeleteDoctor_Click"
                        OnRowCommand="SelectCommand"
                        CssClass="table  table-hover table-striped table-bordered dataTable text-center "
                        runat="server"

                        CaptionAlign="Top"
                        HorizontalAlign="Center"
                        CellSpacing="3"
                        AutoGenerateSelectButton="True">

                        <SelectedRowStyle CssClass="table-primary" />
                        <SortedAscendingCellStyle BackColor="#F7F7F7" />
                        <SortedAscendingHeaderStyle BackColor="#487575" />
                        <SortedDescendingCellStyle BackColor="#E5E5E5" />
                        <SortedDescendingHeaderStyle BackColor="#275353" />

                    </asp:GridView>
                </div>

            </div>
            <div class="col-auto text-left pt-4" runat="server" id="mydiv">
            </div>

        </div>














    </form>
</asp:Content>
