<%@ Page Title="" Language="C#" MasterPageFile="~/Doctor/doctormaster.Master" AutoEventWireup="true" CodeBehind="PendingAppointment.aspx.cs" Inherits="doctor.pendingappointment" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>Pending Appointments</title>
</asp:Content>



<asp:Content ID="Content2" ContentPlaceHolderID="Cp3" runat="server">


    <h2 class="font-weight-bold">Pending Appointments

    </h2>
    <hr />

    <div class="table-responsive">



        <asp:GridView  EmptyDataText="No data available" ID="pendingappointments" class="GridView-d"
            runat="server"
            AutoGenerateSelectButton="True"
            AutoGenerateDeleteButton="True"
            EnableViewState="False"
            OnRowCommand="update_appointment"
            OnRowDeleting="Delete_appointment"
            CellPadding="4"
            CssClass="table  table-hover table-striped table-bordered dataTable text-center "
            HorizontalAlign="Center"
            GridLines="Vertical">

            <SelectedRowStyle CssClass="table-primary" />
            <SortedAscendingCellStyle BackColor="#FBFBF2" />
            <SortedAscendingHeaderStyle BackColor="#848384" />
            <SortedDescendingCellStyle BackColor="#EAEAD3" />
            <SortedDescendingHeaderStyle BackColor="#575357" />
        </asp:GridView>
    </div>
</asp:Content>
